### ISSUE TITLE
Need way to specify skip-level parent relationships

### ISSUE THREAD

**Issue by yangchristian** [CrossLead/tyranid-gracl#13]
Say you have the following `Resource` hierarchy:
* Organization
  * Group
    * User

Modeled as:
```js
const Organization = new Tyr.Collection({
  name: 'organization',
  ...
};

const Group = new Tyr.Collection({
  name: 'group',
  fields: {
    organizationId: {
      link: 'organization',
      relate: 'ownedBy',
      direction: 'outgoing',
      graclType: [ 'resource' ]
    },
    ...
  },
  ...
};

const User = new Tyr.Collection({
  name: 'user',
  fields: {
    organizationId: { link: 'organization' },
    groupIds:       { is: 'array',
                      of: {
                        link: 'group',
                        relate: 'ownedBy',
                        direction: 'outgoing',
                        graclType: [ 'resource' ]
                      }
                    },
    ...
  },
  ...
}
```

If I grant a permission on the top level parent (`Organization` in this case), `User`s in that `Organization` but **not** in an intermediate `Group` won't inherit the permission.

**Comment by bsouthga** [comment]
I think this can be added without too much of a change to the codebase. Basically, if a collection has a parent, and no ids for the parent, I will check if the next level parent has a "path" to the original collection, if not, recurse to the next parent.

**Comment by bsouthga** [comment]
The above fix will not be totally complete however, for something like the following:

Say we have the following schema
```
user -> teams -> org
       `-> regions -> org
       `-> org
```
That is that user has teams and regions, which both have orgs, as well as a direct orgId

Additionally, lets say the gracl hierarchy is as follows

```
user -> teams -> orgs
```

finally, assume that the user doesn't have any team ids or organization id, but it does have regions.

The above fix will first look for teams, will find none, and then look for the shortest path
between the next link in the gracl hierarchy (orgs) and user, which should just be user.organizationId.
however, since there is no direct organizationId set on the user, it will find nothing, and thus return no parents and stop the recursive check.

However, we ideally would also want to use the path from user-> region -> organization. The problem
is that this essentially requires enumerating all possible paths between user and organization which
becomes an `O(2^n)` problem. Right now we are just storing the shortest paths, which can
be pre-computed in `O(n^3)` time.

**Comment by bsouthga** [comment]
Alternatively, I suppose we could use some sort of constrained pathfinding algorithm which would exclude the links that are not available (and finds an alternative path to the end collection) -- this is beyond the scope of the above specific problem though, and can be addressed later

**Comment by bsouthga** [comment]
Discussed solution to this bug implemented here: https://github.com/CrossLead/tyranid-gracl/commit/fbce79ac3e73993dff342111060e41f9be78d811
